repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    - id: autopep8
      args: ["--max-line-length=120", "--ignore=E401,E266", "-i"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: end-of-file-fixer
    - id: check-yaml
    - id: debug-statements
    - id: flake8
      args: ["--ignore=E225,E266,E231,E401,E501,F401"]
    - id: check-added-large-files
