# Generated by Django 2.1.7 on 2019-02-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='is_authorized',
            field=models.IntegerField(null=True),
        ),
    ]
